"""added Player table

Revision ID: 58c81ec8c2b9
Revises: 
Create Date: 2021-12-20 14:05:24.306619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c81ec8c2b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('mpg', sa.Float(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Float(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Float(), nullable=True),
    sa.Column('thpa', sa.Integer(), nullable=True),
    sa.Column('thpp', sa.Float(), nullable=True),
    sa.Column('ppg', sa.Float(), nullable=True),
    sa.Column('rpg', sa.Float(), nullable=True),
    sa.Column('apg', sa.Float(), nullable=True),
    sa.Column('spg', sa.Float(), nullable=True),
    sa.Column('bpg', sa.Float(), nullable=True),
    sa.Column('topg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
